# This is purely an example.
# It is a good practice to leave passwords empty in this file and manually type it when prompted.
# Your password will NOT be shown in console while typing.
---
production:
  username: foo@bar.com
  password: foobarpassword
  security_token: adwk2udj29
developer:
  username: foodev@bar.com
  password: foobardevpassword
  security_token: jiejw2udj29
